### ISSUE TITLE
Unable to proxy to complex services (like jellyfin, invoiceNinja)

### ISSUE THREAD

**Issue by crimue** [boringproxy/boringproxy#8]
Hello, first of all: **Seems to be an awesome piece of software!** 

I just have one problem: Simple services like a http-webserver work fine. But services like Jellyfin or InvoiceNinja do not work. With Jellyfin I am able to get to the login and after that it throws an "jellyfin server not found" error. InvoiceNinja only redierects me to /login and than throws connection refused. 

Is boringproxy not meant for complex services? Or do I miss something? (Demo instance: https://bpdemo.brng.pro was used).

Thank you very much
Christian

**Comment by anderspitman** [comment]
Thanks for the report, Christian.

It should work for any web service,  regardless of complexity. However, I've only tested it on a handful so far, so there are likely to be some rough edges to smooth out. My first guess is those services may require WebSockets support, which there's a good chance isn't working yet. I'll give Jellyfin a try and report back what I find.

**Comment by crimue** [comment]
Thank you very much for your fast response! Looking forward to your results and feel free to contact me if you need help with the debugging.

**Comment by anderspitman** [comment]
Ok I dig some quick debugging with Jellyfin. I can confirm that it doesn't work when I try to login. Here's what I learned:

* HTTP localhost:8096 works
* HTTPS behind nginx works
* HTTP boringproxy (ie "Allow External TCP" and connecting directly to the port) also works
* HTTPS boringproxy does not work.

I didn't see anything obviously wrong with the request. I'm guessing there's some expect reverse proxy headers that I'm not sending. This is going to take some deeper debugging.

**Comment by anderspitman** [comment]
Alright I believe I have fixed it. Can you try this release and let me know if it works for you?

https://github.com/boringproxy/boringproxy/releases/tag/v0.1.1

**Comment by anderspitman** [comment]
Oh actually that's not necessary to test, since the client wasn't the problem. I just need to update the demo instance real quick. One second.

**Comment by anderspitman** [comment]
Ok demo instance is ready for you to test. Let me know how it goes.

**Comment by crimue** [comment]
Wow crazy. Jellyfin does now work perfectly! Really impressive. Thank you! Sadly InvoiceNinja and Portainer still do not work.

**Comment by anderspitman** [comment]
No problem. These bug reports are very useful!

My gut feeling for InvoiceNinja and Portainer is WebSockets. Unfortunately both of them look more complicated to run than Jellyfin, which has a nice simple docker image.

Would it be possible for you to try running them with your browser devtools open (F12) to the network tab, and send me a screenshot of the requests that are failing, if any?

**Comment by crimue** [comment]
The Portainer errors:
![portainer](https://user-images.githubusercontent.com/26869511/98044791-bbe77c80-1e27-11eb-8887-7da58da6a1d1.PNG)

The Invoice Ninja redirect. Maybe this can not be fixed on your side?:
![invoiceNinja](https://user-images.githubusercontent.com/26869511/98044778-b5590500-1e27-11eb-98f3-896c4f735f8e.PNG)

Both are running in docker containers. Thank you again.

**Comment by anderspitman** [comment]
Thanks. Looks like it's not WebSockets, although I'm pretty sure I'll have to do some significant work on those eventually.

Not sure what's going on with Portainer. The InvoiceNinja looks like it may be assuming it runs on localhost, and generating its redirect URLs based on that? You might check and see if there's a way to set custom domains in the InvoiceNinja configuration.

Either way it looks like it won't be a quick fix. I'll see if I can get Portainer up and running to debug directly, but it'll probably take some time.

**Comment by crimue** [comment]
Some news: I tried a "normal" reverse proxy (https://docs.linuxserver.io/general/swag) with invoice ninja but I only get "bad redirect" with nginx. Portainer works with swag. Maybe invoiceNinja works with boringproxy and my setup is somehow broken. Even a fresh install (with the brng.pro domain/url) makes weird localhost redirects. Just a little note.

Stability seems to be really good. First jellyfin stress test was a success!

**Comment by anderspitman** [comment]
Interesting. There's a good chance boringproxy is still doing strange things with redirects. I already had one bug with that a few days ago. Just to clarify, Portainer still isn't working on boringproxy, right?

**Comment by anderspitman** [comment]
Aha! I found a bug that is very likely to be causing these issues. Basically I was intercepting all calls to `/api/` endpoints, not just those meant for the admin UI. Which means that if a proxied server uses the same `/api/` convention (which is very common), the call will go to the boringproxy api and certainly fail. I've confirmed this fixes FileBrowser (which wasn't working for me). I don't have time to test it now, but according to the documentation, Portainer also uses `/api/`. There's a really good chance this will fix it. Can you try again?

**Comment by crimue** [comment]
Awesome! I can confirm that portainer is now working flawlessly. Great work!

**Comment by anderspitman** [comment]
Excellent! Any luck with InvoiceNinja. I see they also use `/api` so we might get lucky.

**Comment by anderspitman** [comment]
So I'm playing with Nextcloud right now, and it's doing some goofy 127.0.0.1 redirects, so I suspect InvoiceNinja won't work yet either. But I think we're close.

**Comment by anderspitman** [comment]
Ok I resolved the Nextcloud issues by setting some environment variables. This script works behind boringproxy:

```bash
docker run \
        --rm -it -p 8080:80 \
        --env NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.brng.pro \
        --env OVERWRITEHOST=nextcloud.brng.pro \
        --env OVERWRITEPROTOCOL=HTTPS \
        nextcloud
```

I still think I may need to be sending more of the usual reverse proxy headers though. Currently only sending `X-Forwarded-Host`. I'll open an issue for adding more.

**Comment by crimue** [comment]
I tried to rebuild the InvoiceNinja Docker container with the env-var `TRUSTED_PROXIES='https://devgarten.brng.pro/,172.0.0.0'` (according to https://invoice-ninja.readthedocs.io/en/latest/configure.html#using-a-reverse-proxy) but redirects are still occuring.

The docker log (not that much...):
`web_1   | 172.23.0.1 - - [06/Nov/2020:13:39:32 +0000] "GET / HTTP/1.1" 302 364 "-" "Mozilla/5.0 (Windows N..,. BROWSERINFOS")
app_1   | 172.23.0.5 -  06/Nov/2020:13:39:32 +0000 "GET /index.php" 302`

Thank you very much! Maybe we should create a list of working apps and specific configurations (like in your nextcloud example)?

**Comment by almereyda** [comment]
I like the idea of a showcase of working configuration examples. Would the
GitHub repository wiki suffice for that?

**Comment by anderspitman** [comment]
I like this idea as well, at least for major software like Nextcloud. We want to be careful not to end up maintaining duplicated documentation for other projects though. I think a page explaining the basic problem, a few examples for things like Nextcloud, and then links to a few more should do it. I'd prefer to avoid GitHub vendor lock-in as much as possible though, with the wiki. I think we could probably add it as pages on https://github.com/boringproxy/boringproxy.io.

**Comment by voarsh2** [comment]
I think you should add caprover (https://github.com/caprover/caprover) to the list.

**Comment by voarsh2** [comment]
I've been trying to get caprover working with boringproxy for like 3 days.
https://github.com/caprover/caprover/issues/901

Port forwarding isn't the answer?
It doesn't matter what I port forward, because my ISP has be behind a NAT, I'm on a mobile hotspot.

**Comment by voarsh2** [comment]
Just chiming in, I got Jellyfin working on non HTTPS.

**Comment by voarsh2** [comment]
I am not sure what happened but I get this:
![image](https://user-images.githubusercontent.com/60437695/104210115-67b1d780-542a-11eb-905d-8a0e0880608c.png)

![image](https://user-images.githubusercontent.com/60437695/104210221-8617d300-542a-11eb-91b4-5d8c17d4d2cf.png)


Also, relating to another issue: SyncPlay
https://github.com/boringproxy/boringproxy/issues/35#issue-782877778

**Comment by anderspitman** [comment]
Going to close this. If anyone has outstanding problems with specific services please open a new issue (or comment on another one if it already exists).
